name: Simple Runnner

on:
  push:
    branches:
      - main
    workflow_dispatch:

jobs:
    run:
        runs-on: self-hosted
        steps:
          -  name: Log
             run: echo "Build Start"
             
          -  name: Run APK Build
             run: /Users/kitamura/Documents/CD-CI-Test/buildAPK.sh
             
          -  name: Run AAB Build
             run: /Users/kitamura/Documents/CD-CI-Test/buildAAB.sh
             
          -  name: Run iOS Build
             run: /Users/kitamura/Documents/CD-CI-Test/buildIOS.sh
             
