name: Simple Runnner

on: push:
    workflow_dispatch:

jobs:
    run:
        runs-on: self-hosted
        steps:
          -  name: Log
             run: echo "Build Start"
             
          -  name: Run Build
             run: ../../build.sh
